apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: final
data:

  STUDENT_NAME: "Bahar & Philip & Tony"

  BG_IMAGE_URL: "s3://bucket-743872963550/background.jpg"

  DATABASE: "employees"

  DBHOST: "mysql-service.final.svc.cluster.local"

  DBPORT: "3306"
